#!/usr/bin/python3
print("HTTP/1.1 200 OK\r")
print ("Content-Type: text/html\r\n\r")
print('<!DOCTYPE html>')
print ('<html>')
print ('<head>')
print ('<title>Hello Word - First CGI Program</title>')
print ('</head>')
print ('<body>')
print ('<h2>Hello Word! This is my first CGI program</h2>')
print ('</body>')
print ('</html>')
